default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  # POSTGRES_PASSWORD
  password: ***
  pool: 5

development:
  <<: *default
  database: albuminfos

test:
  <<: *default
